### PR TITLE
About update

### PR DESCRIPTION
**Pull request by imuchnik**
@keithpif Please review and merge

### CODE REVIEW

**Comment by keithpif** [comment]
@imuchnik I'm still seeing some data files in here. Can you remove them?

shared_files/readme_start_here/readme_Results_Presentation2.pptx
shared_files/readme_start_here/readme_platelets_example2.docx
shared_files/shared_external.zip

**Comment by imuchnik** [comment]
@keithpif where do you see them? I don't have them in my fork. I see the them removed in 470e094401fcd commit.

**Comment by keithpif** [comment]
At the bottom of this: https://github.com/presidential-innovation-fellows/tophealth/pull/8/commits/6c22a735b1fae763000eabdd763f8e4b20a04c9c

**Comment by imuchnik** [comment]
They are being  deleted with the rest of the folder on the bottom of that commit.

**Pull request merged**
